name: Makefile CI

# 03725 - https://github.com/roseswe/tainted/security/code-scanning/26
permissions:
  contents: read
  pull-requests: write

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build Executable
      run: make

    - name: Upload binary
      uses: actions/upload-artifact@v4
      with:
        name: tainted
        path: ./tainted
