name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build Executable
      run: make

    - name: Upload binary
      uses: actions/upload-artifact@v3
      with:
        name: tainted
        path: ./tainted
