## 22.02.2023
name: Compile and Release
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install build-essential
        run: sudo apt-get install -y build-essential gcc
      - name: Compile C code
        run: make
      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v2.0.0
          release_name: Release v2.0.0
          body: |
            A new release of the code has been created.
          draft: false
          prerelease: false
      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: tainted
          path: ./tainted
