## 22.02.2023
## Not working yet!
## See also:  https://github.com/actions/upload-release-asset, https://github.com/search?q=github+release+actions
## https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/

name: Compile and Release
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install build-essential
        run: sudo apt-get install -y build-essential gcc
      - name: Compile C code
        run: make
      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            A new release of the code has been created.
          draft: false
          prerelease: false
      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: tainted
          path: ./tainted
